// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkvGdlj5YZfibVaLHARSbTvSnDmX8nhds',
    appId: '1:663200417303:web:3eeb0d220686303168be52',
    messagingSenderId: '663200417303',
    projectId: 'follow-373604',
    authDomain: 'follow-373604.firebaseapp.com',
    storageBucket: 'follow-373604.appspot.com',
    measurementId: 'G-HE3WZ9FQME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxcDRV_C8tPpyxqnhiWAEnzILB4G5Xqso',
    appId: '1:663200417303:android:31b5af30d93b041c68be52',
    messagingSenderId: '663200417303',
    projectId: 'follow-373604',
    storageBucket: 'follow-373604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKPEA1YHAIzF-kmwRDTTihizTnvAqe-1w',
    appId: '1:663200417303:ios:e1cee54bcedea3c568be52',
    messagingSenderId: '663200417303',
    projectId: 'follow-373604',
    storageBucket: 'follow-373604.appspot.com',
    iosClientId: '663200417303-hrgs6u4u7h1mr14pcfpf3qtq3tht90cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.follow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKPEA1YHAIzF-kmwRDTTihizTnvAqe-1w',
    appId: '1:663200417303:ios:e1cee54bcedea3c568be52',
    messagingSenderId: '663200417303',
    projectId: 'follow-373604',
    storageBucket: 'follow-373604.appspot.com',
    iosClientId: '663200417303-hrgs6u4u7h1mr14pcfpf3qtq3tht90cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.follow',
  );
}
